### ISSUE TITLE
Secure POST /boards/{id}/messages

### ISSUE THREAD

**Issue by mbret** [mbret/pulseboard#18]
back:
- add limit to name, content
- return 400 if they are not followed by request

front:
- add same limit as back end

@nbusser si tu peux mettre les limites dans un fichier de conf ou env comme ca je peux utiliser les memes sur le front

**Comment by nbusser** [comment]
`NAME_LENGTH_LIMIT` et `MESSAGE_LENGTH_LIMIT`, à mettre dans ton env.  
Si pas défini, pas de limite

**Comment by nbusser** [comment]
Added basic file limitation. To be improved in https://github.com/mbret/pulseboard/issues/20
